#!/bin/python3

"""
forward is the ufw of port forwarding.

Please note that port forwarding will ignore firewall rules created with ufw.
"""

# TODO: validate input (in parse_port_forward)

# TODO: allow specifying outgoing interface
# iptables syntax: iptables -I FORWARD -o virbr1 -p udp -d $GUEST_IP --dport $GUEST_PORT -j ACCEPT

# TODO: when the interface is set, add a nat MASQUERADE rule to tag the trafic as coming from this machine ?
# (without this, port forwarding only works if the forwarding machine is the gateway, since trafic will still be marked as coming from the original source)

import sys
from dataclasses import dataclass

from subprocess import Popen, PIPE, STDOUT


"""
library
"""


# copy pasted from https://github.com/lispydev/disk-replicator
# TODO: when stderr is False, merge stderr with stdout
# (this version just ignores stderr)
def system(cmd, stdin=None, stderr=False):
    """
    usage:
    stdout[, stderr], errcode = system(command[, stdin][, stderr=True])
    """
    # merge stdout and stderr, and return error code instead
    if stdin is not None:
        stdin = stdin.encode()
    process = Popen(cmd, shell=True,
                    stdout=PIPE,
                    stderr=PIPE if stderr else STDOUT)
    out, err = process.communicate(stdin)
    returncode = process.returncode
    if stderr:
        return out.decode(), err.decode(), returncode
    else:
        return out.decode(), returncode




# a port forward as described by the user
# TODO: get better at finding names
# TODO: link port forward rules with iptables rewrite and forward rules
@dataclass
class Rule:
    src_port: int
    dst_address: str
    dst_port: int
    protocols: list


# port forward rules as described by iptables (packet rewrites and packet forwards)
@dataclass
class Rewrite:
    src_port: int
    dst_address: str
    dst_port: int
    protocol: str

    index: int

@dataclass
class Forward:
    src_port: int
    dst_address: str
    dst_port: int
    protocol: str

    index: int


# TODO: refactor (iptables comments are used many times)
def comment_marker(rule):
    pass


"""
iptables manipulation helpers

these helpers are not safe for user input.



Some random notes about iptables:

On tables:
iptables rules are split into tables (filter, nat,...).
Every iptables command operates on a table,  specified with -t <table>
if -t is not specified, the default table is filter.
with iptables, available tables are hardcoded by the kernel:
    filter
    nat
    mangle
    raw
    security (SELinux)

portforward operates on filter and nat tables.

On chains:
inside a table, rules are sorted into chains.
inside a chain, rules are executed procedurally.
while rules can be put into builtin chains such as FORWARD,
but using dedicated chains helps manageing rules without breaking things.
The builtin chains and custom ones behave differently.

Builtin chains:
builtin chains have a policy for packets that match no rule. By default, this policy is always ACCEPT, but it can be changed by software (ufw sets the filter policy to DROP for input and forward trafic).
The builtin chains are:
    in the filter table:
        INPUT
        FORWARD
        OUTPUT
    in the nat table
        PREROUTING
        INPUT
        OUTPUT
        POSTROUTING
    mangle:
        PREROUTING
        INPUT
        FORWARD
        OUTPUT
        POSTROUTING
    raw:
        PREROUTING
        OUTPUT
    security:
        INPUT
        FORWARD
        OUTPUT
Policies can be:
    ACCEPT
    DROP
    REJECT (same as drop, but sends an error response with ICMP or TCP reset)
    (More detailed behaviour is possible within rules, where the "target" is the action done on the packet)

The policy of a builtin chain can be set with iptables -P <chain> <policy>


Custom chains:
Custom chains can be hooked to other chains so that their rules are executed as part of the parent chain, with a jump.
For example: iptables -t filter -A INPUT -j on-input-rules
Rules in custom chains are executed in order, and can RETURN to the parent chainto interrupt execution
Example: iptables -A on-input-rules -j RETURN
Chain jumps are actually just rules with a chain as their target, so it is possible to make conditional logic by adding filters on the jump rules
Example: iptables -A INPUT -p tcp -dport 22 -j ssh-chain
Though the applications seem limited to packet-level logic (i can't see any use for loops, for example)

For higher level stateful packet processing, see NFQUEUE (allows sending the packet to a userspace program to decide what to do with it).


On rules:
A rule must always have a target to jump to (-j).
Without explicit filters, a rule matches everything going through it and always executes.
Iptables accepts a rule description after these commands:
    -A append (most common, appends a rule at the end of a chain)
    -I insert (-I <chain> [<position>])
    -R replace
    -D delete
Basic rule definition examples:
    iptables -A my-chain -j ACCEPT
    which means: accept all packets sent to my-chain in the filter table
    iptables -A my-chain -j RETURN
    which means: after doing everything in my-chain, return
        note: this is already the default behavior of iptables, so this rule is a no-op
For more advanced rules, most filtering features must be explicitely loaded with -m <module> before using it:
        -m tcp (tcp options: ports, flags)
        -m udp (udp options: ports)
        -m mac (mac address)
        -m state (connection state: NEW or ESTABLISHED)
        ...




Some examples of iptables commands:
chain management:
iptables -N portforward # create a portforward chain in the filter table
iptables -X portforward # delete it
iptables -t nat -N portforward # same, but in the nat table
iptables -X portforward -t nat

iptables -P INPUT DROP  # drop all incoming packets (set by ufw)
iptables -P FORWARD DROP  # drop all packets to route (set by ufw)

The policy of a builtin chain can be set with iptables -P <chain> <policy>

Rules:
iptables -A <chain> -j <target> # adding a rule
Jump rules:
iptables -A some-chain -j my-new-chain

Other actions can be considered as just jumps to builtin targets:
iptables -A my-chain -j ACCEPT  # accept packets sent through my-chain
iptables -A my-chain -j RETURN  # return from my-chain
iptables -I my-chain 3 -j RETURN  # insert an early return at position 3
    note: rules are indexed starting at 1
    (-I my-chain without an index is the same as -I my-chain 1)

Filters and target arguments are sent as cli parameters:
# the rule applies to packets with a destination port 22 that are marked with 1
# and rejects them with a tcp-reset answer
iptables -t mangle -A PREROUTING --dport 22 -m mark --mark 1 -j REJECT --reject-with tcp-reset

Replace:
iptables -R my-chain 2 -j DROP  # replace the 2nd rule in my-chain with a new drop rule

Deletion:
iptables -D my-chain 2  # delete the second rule
iptables -D my-chain -p tcp -j ACCEPT  # delete the rule by describing it exactly



"""


# helper for building iptables commands
def scope(name="filter"):
    if name is None:
        name = "filter"
    return f"-t {name}"

def chain_exists(name, table=None):
    cmd = f"iptables {scope(table)} -L {name}"
    #print(cmd)
    out, code = system(cmd)
    success = (code == 0)
    return success

def create_chain(name, table=None):
    #if not chain_exists(name, table):
    cmd = f"iptables {scope(table)} -N {name}"
    out, code = system(cmd)
    return (code == 0)

# will not delete the chain if there are rules or jumps using it
# (empty the chain first with empty_chain(), and remove the chain jumps)
def delete_chain(name, table=None):
    cmd = f"iptables {scope(table)} -X {name}"
    out, code = system(cmd)
    return (code == 0)

def empty_chain(name, table=None):
    cmd = f"iptables {scope(table)} -F {name}"
    #print(cmd)
    out, code = system(cmd)
    #print(out, code)
    return (code == 0)

# tests used while writing the code
#print(create_chain("portforward"))
#print(create_chain("portforward"))
#print(chain_exists("portforward"))
#print(delete_chain("portforward"))


"""
Dataclass wrapper over IPTables rules
"""

# TODO: add options as needed
class IptablesRule:
    jump_target: str

    def __str__(self):
        return f"-j {self.jump_target}"

    # TODO: find a better API
    # for now, use functions
    #def insert_at(self, chain, position=None, table=None):
    #    return f"-t {scope(table)} -A {chain} {str(self)}"

    def append_to(self, chain, table=None):
        return f"-t {scope(table)} -A {chain} {str(self)}"

    def delete_from(self, chain, table=None):
        return f"-t {scope(table)} -D {chain} {str(self)}"

def jump(chain):
    return f"-j {chain}"

def append(chain):
    return f"-A {chain}"

def insert(chain, position=1):
    if position is None:
        position = 1
    return f"-I {chain} {position}"

# delete rule by index
# TODO: never use this, as this is more error-prone than delete()
def delete_index(chain, position):
    return f"-D {chain} {position}"

# delete rule by rule spec
# (helper for command generation)
def delete(chain):
    return f"-D {chain}"


# insert chains into filter/FORWARD and nat/PREROUTING
def insert_chain_jump(where, chain, table=None):
    cmd = f"iptables {scope(table)} {insert(where)} {jump(chain)}"
    #print(cmd)
    out, code = system(cmd)
    return code == 0

def delete_chain_jump(where, chain, table=None):
    cmd = f"iptables {scope(table)} {delete(where)} {jump(chain)}"
    #print(cmd)
    out, code = system(cmd)
    return code == 0


#print(create_chain("portforward"))
#print(insert_chain_jump("FORWARD", "portforward"))
#print(delete_chain("portforward"))

#print(create_chain("portforward", "nat"))
#print(insert_chain_jump("PREROUTING", "portforward", "nat"))
#print(delete_chain("portforward"))


def define_chains():
    if not chain_exists("portforward"):
        create_chain("portforward")
        assert chain_exists("portforward")
        insert_chain_jump("FORWARD", "portforward")
    if not chain_exists("portforward", table="nat"):
        create_chain("portforward", "nat")
        assert chain_exists("portforward", "nat")
        insert_chain_jump("PREROUTING", "portforward", "nat")

def remove_chains():
    if chain_exists("portforward"):
        #cmd = f"iptables -D FORWARD -t filter -j portforward"
        delete_chain_jump("FORWARD", "portforward")
        delete_chain("portforward")
    if chain_exists("portforward", table="nat"):
        delete_chain_jump("PREROUTING", "portforward", "nat")
        delete_chain("portforward", "nat")
    assert not chain_exists("portforward")
    assert not chain_exists("portforward", "nat")


#print(chain_exists("portforward"))
#print(chain_exists("portforward", "nat"))
#define_chains()
#print(chain_exists("portforward"))
#print(chain_exists("portforward", "nat"))
#remove_chains()
#print(chain_exists("portforward"))
#print(chain_exists("portforward", "nat"))



"""
status management

operations:
    -get status (enabled or disabled)
    -enable
    -disable

TODO:
    -persistence of enable (with a service ?)
    -database of rules to enable during activation
    -flush all rules on disable
    -restore/remove rules
"""

# Database operations

# TODO: use posix paths (/var/lib/portforward,...)
db_path = "ports.json"

default_config = {
    "enabled": False,
    "ports": [],
}

def read_db():
    if not os.path.exists(db_path):
        return default_config
    with open(db_path) as f:
        return json.load(f)

def write_db(config):
    with open(db_path, "w") as f:
        json.dump(f, config)


# high level iptables and db operations



# check if chains are defined
def is_enabled():
    return chain_exists("portforward")

# edit the database
def set_enabled(enabled: bool):
    config = read_db()
    config["enabled"] = enabled
    write_db(config)

def enable():
    define_chains()
    # TODO: define rules

def disable():
    # cleanup rules
    if chain_exists("portforward"):
        assert empty_chain("portforward")
    if chain_exists("portforward", "nat"):
        assert empty_chain("portforward", "nat")
    # cleanup chains
    remove_chains()


#print(is_enabled())
#enable()
#print(is_enabled())
#disable()
#print(is_enabled())




"""
arg parsing
"""

# argument parsing ("add port ... to ...:... proto ...", "del port ...")
def parse_port_forward(argv):
    args = {
        "src-port": None,
        "dst-addr": None,
        "dst-port": None,
        "protocol": None,
        #"src-iface": None,
    }
    i = 0
    while i < len(argv):
        kw = argv[i]
        if kw == "proto":
            args["protocol"] = argv[i + 1]
            i += 2
        elif kw == "port":
            args["src-port"] = argv[i + 1]
            i += 2
        elif kw == "to":
            destination = argv[i + 1]
            if ":" in destination:
                dst_addr, dst_port = destination.split(":")
                args["dst-addr"] = dst_addr
                args["dst-port"] = dst_port
            else:
                args["dst-addr"] = destination
                # set after finishing arg parsing
                args["dst-port"] = "=src-port"
            i += 2
        #elif kw == "from":
        #    #src_interface = argv[i + 1]
        #    # list the physical interfaces
        #    interfaces = system("ip -o link show | cut -d ':' -f 2")[0]
        #    interfaces = interfaces.split("\n")[:-1]
        #    interfaces = [line.strip() for line in interfaces]
        #    if src_interface in interfaces:
        #        args["src-iface"] = src_interface
        #    else:
        #        raise ValueError(f"Unknown interface: {src_interface}, expected one among {interfaces}")
        #    i += 2
        else:
            print(f"Error: Unexpected argument '{kw}'")
            usage()


    # post-processing
    if args["src-port"] is None:
        print("Error: Expecting a port to forward")
        usage()

    if args["dst-port"] == "=src-port":
        args["dst-port"] = args["src-port"]

    if args["protocol"] is None:
        args["protocols"] = ["tcp", "udp"]
    elif args["protocol"] == "tcp":
        args["protocols"] = ["tcp"]
    elif args["protocol"] == "udp":
        args["protocols"] = ["udp"]
    else:
        proto = args["protocol"]
        raise ValueError(f"Unknown protocol '{proto}'")

    return args

def parse_add(argv):
    args = parse_port_forward(argv[2:])

    # TODO (for clarity): use a dictionary ? (subcommand(**kwargs) or subcommand(args))
    #return args
    assert args["dst-port"] != "=src-port", "internal integrity check"
    return [args["src-port"], args["dst-addr"], args["dst-port"], args["protocols"]]#, args["src-iface"]]

def add(src_port, dst_addr, dst_port, protocols):
    for proto in protocols:
        comment_marker = f"portforward: {src_port}/{proto} -> {dst_addr}:{dst_port}"  # used to recognize rules created by this program and identify them
        #if src_interface is not None:
        #    iface_spec = f"-i {src_interface}"
        #else:
        #    iface_spec = ""
        #packet_rewrite = f"iptables -t nat -I PREROUTING {iface_spec} -p {proto} --dport {src_port} -j DNAT --to {dst_addr}:{dst_port} -m comment --comment \"{comment_marker} (rewrite to forwarded packet)\""
        packet_rewrite = f"iptables -t nat -I PREROUTING -p {proto} --dport {src_port} -j DNAT --to {dst_addr}:{dst_port} -m comment --comment \"{comment_marker} (rewrite to forwarded packet)\""
        packet_forward = f"iptables -I FORWARD -p {proto} -d {dst_addr} --dport {dst_port} -j ACCEPT -m comment --comment \"{comment_marker} (accept forwarded packet)\""

        print(packet_rewrite)
        print(packet_forward)
        #print(system(packet_rewrite))
        #print(system(packet_forward))
        out, code = system(packet_rewrite)
        if code != 0 or out != '':
            print('error during port forwarding:')
            print('return code:', code)
            print('error:')
            print(out)
            print('aborting after', packet_rewrite)
            return
        out2, code2 = system(packet_forward)
        if code2 != 0 or out2 != '':
            print('error during port forwarding:')
            print('return code:', code2)
            print('error:')
            print(out2)
        if code == 0 and out == '' and code2 == 0 and out2 == '':
            print('ok')

    

def parse_rewrite(line):
    print(line)
    # line format:
    # 1 502 28252 DNAT tcp -- * * 0.0.0.0/0 0.0.0.0/0 tcp dpt:443 /* portforward: 443/tcp -> 192.168.122.5:443 (rewrite to forwarded packet) */ to:192.168.122.5:443
    # TODO: new format:
    # 1 502 28252 DNAT tcp -- eno1 * * 0.0.0.0/0 0.0.0.0/0 tcp dpt:443 /* portforward: 443/tcp -> 192.168.122.5:443 (rewrite to forwarded packet) */ to:192.168.122.5:443
    # TODO: improve comments with interface annotations
    #fields = line.split(" ", 12)
    #index = int(fields[0])
    #comment = fields[-1]  # wrong, since there is "to:192.168.122.5:443" at the end of the rule
    index, _ = line.split(" ", 1)
    index = int(index)
    _, comment = line.split("/* ")
    comment, _ = comment.split(" */")
    # comment format:
    # portforward: 8000/tcp -> 192.168.122.5:8000 (rewrite to forwarded packet)
    parts = comment.split(" ", 4)
    _, source, _, dest, _ = parts
    source_port, protocol = source.split("/")
    dest_address, dest_port = dest.split(":")

    rewrite = Rewrite(source_port, dest_address, dest_port, protocol, index)
    return rewrite


def parse_forward(line):
    # line format:
    # 6 12024 1342K ACCEPT udp -- * * 0.0.0.0/0 192.168.123.2 udp dpt:53637 /* portforward: 53637/udp -> 192.168.123.2:53637 (accept forwarded packet) */
    fields = line.split(" ", 12)
    index = int(fields[0])
    comment = fields[-1]

    # comment format:
    # /* portforward: 443/tcp -> 192.168.122.5:443 (accept forwarded packet) */

    # remove /* */
    comment = comment[3:-3]
    parts = comment.split(" ", 4)
    _, source, _, dest, _ = parts
    source_port, protocol = source.split("/")
    dest_address, dest_port = dest.split(":")

    forward = Forward(source_port, dest_address, dest_port, protocol, index)
    return forward


def read_iptables():
    # parse output from iptables
    list_rewrites = 'iptables -t nat -L PREROUTING -n -v --line-numbers | grep "portforward:" | tr -s " "'
    list_forwards = 'iptables -L -n -v --line-numbers | grep "portforward:" | tr -s " "'

    out, code = system(list_rewrites)
    assert code == 0
    lines = out.split("\n")[:-1]
    rewrites = [parse_rewrite(line) for line in lines]

    out, code = system(list_forwards)
    assert code == 0
    lines = out.split("\n")[:-1]
    forwards = [parse_forward(line) for line in lines]

    return (rewrites, forwards)

# TODO: organize rules better than this (should be able to find iptables rules from the user-facing port forward rules)
def sort_rules(rewrites, forwards):
    # convert iptables rules into a list of port forwarding Rules
    # rewrites and forwards contain the same information, so forwards are ignored
    port_forwards = {}  # port -> Rule
    #iptables = {}  # port -> proto -> [rewrite, forward] (used to find iptables rules from port forward rules)
    for r in rewrites:
        #iptables.setdefault(r.src_port, {})
        #iptables[r.src_port].setdefault(r.protocol, [])
        #iptables[r.src_port][r.protocol].append(r)

        if r.src_port in port_forwards:
            port_forwards[r.src_port].protocols.append(r.protocol)
        else:
            port_forwards[r.src_port] = Rule(r.src_port, r.dst_address, r.dst_port, [r.protocol])
    #for f in forwards:
    #    iptables.setdefault(f.src_port, {})
    #    iptables[f.src_port].setdefault(f.protocol, [])
    #    iptables[f.src_port][f.protocol].append(f)
    return [port_forwards[port] for port in port_forwards]#, iptables

# the "list" command
def print_rules():
    rewrites, forwards = read_iptables()
    rules = sort_rules(rewrites, forwards)
    for rule in rules:
        if len(rule.protocols) == 2:
            print(f"{rule.src_port} -> {rule.dst_address}:{rule.dst_port}")
        else:
            #assert len(rule.protocols) == 1
            print(f"{rule.src_port}/{rule.protocols[0]} -> {rule.dst_address}:{rule.dst_port}")

def parse_del(argv):
    # TODO: centralize argument syntax parsing ("port ... [to ...:..] [proto ...]")
    args = parse_port_forward(argv[2:])
    #assert args["src-iface"] is None, "Specifying inbound interface in delete rules is not supported"

    # TODO (for clarity): use a dictionary ? (subcommand(**kwargs) or subcommand(args))
    #return args
    return [args["src-port"], args["dst-addr"], args["dst-port"], args["protocols"]]


# TODO: cleanup (hide the iptables commands ?) and repeat testing while refactoring
def remove(src_port, dest_addr, dest_port, protocols):
    # only take src_port and protocols, but accept more details ("forward.py port ... to ...:.. proto tcp")
    rewrites, forwards = read_iptables()
    #rules, by_port = sort_rules(rewrites, forwards)
    rules = sort_rules(rewrites, forwards)
    for rule in rules:
        if src_port == rule.src_port:
            # check additional filters
            if dest_addr is not None and rule.dst_address != dest_addr:
                continue
            if dest_port is not None and rule.dst_port != dest_port:
                continue

            for proto in protocols:
                if proto in rule.protocols:
                    # TODO: select the iptables rewrite and forward and delete them
                    # or generate the line from the port forward Rule)
                    print("found proto", proto)
                    #iptables_rules = by_port[rule.src_port][proto]
                    rm_rewrite = f"iptables -t nat -D PREROUTING -p {proto} --dport {rule.src_port} -j DNAT --to {rule.dst_address}:{rule.dst_port} -m comment --comment \"portforward: {rule.src_port}/{proto} -> {rule.dst_address}:{rule.dst_port} (rewrite to forwarded packet)\""
                    rm_forward = f"iptables -D FORWARD -p {proto} -d {rule.dst_address} --dport {rule.dst_port} -j ACCEPT -m comment --comment \"portforward: {rule.src_port}/{proto} -> {rule.dst_address}:{rule.dst_port} (accept forwarded packet)\""
                    print(rm_rewrite)
                    print(rm_forward)
                    print(system(rm_rewrite))
                    print(system(rm_forward))



def usage():
    print(
            "usage: forward add|list|del [...args]\n"
            "\n"
            "examples:\n"
            "    forward add port 80 to 192.168.122.5:80 [proto tcp]\n"
            "    forward list\n"
            "    forward del port 80 [to 192.168.122.5:80] [proto tcp]"
    )
    sys.exit(0)



def parse_args(argv):
    """
    manual arg parsing

    the only accepted argument forms are:
    forward --help
    forward help
    forward add|list|del [...args]
    """
    if len(argv) < 2:
        usage()

    match argv[1]:
        case "--help" | "help":
            usage()
        case "add":
            add_args = parse_add(argv)
            return add, add_args
        case "list":
            # ignore other arguments for now
            # TODO: parse forms such as "forward list tcp"
            return print_rules, []
        case "del":
            return remove, parse_del(argv)
        case default:
            usage()

if __name__ == "__main__":
    subcommand, subargs = parse_args(sys.argv)
    subcommand(*subargs)

